name: Compile

on:
  workflow_call:
    inputs:
      dryrun:
        type: boolean
        description: Dry run
        required: false
        default: false
      build_env:
        type: string
        description: The environment to build
        required: true
        default: devel
      pr_id:
        type: string
        description: Pull request ID
        required: false
        default: ''
      pr_title:
        type: string
        description: Pull request title
        required: false
        default: ''
      pr_body:
        type: string
        description: Pull request body
        required: false
        default: ''

jobs:
  execute:
    environment:
      name: ${{ inputs.build_env }}
      deployment: false
    runs-on: ubuntu-latest
    container:
      image: nebbiearcane/mudcompiler:latest
      options: --entrypoint ""
    env:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      PR_ID: ${{ inputs.pr_id }}
      PR_TITLE: ${{ inputs.pr_title }}
      PR_BODY: ${{ inputs.pr_body }}
    steps:
      - uses: NebbieArcane/Actions/compile@main
        with:
          build_env: ${{ inputs.build_env }}
          mysql_host: ${{ vars.MYSQL_HOST }}
          mysql_user: ${{ vars.MYSQL_USER }}
          mysql_db: ${{ vars.MYSQL_DB }}
          mysql_password: ${{ secrets.MYSQL_PASSWORD }}
          mysql_port: ${{ vars.MYSQL_PORT }}
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: latest,prerelease,release
          dryrun: ${{ inputs.dryrun }}
          pr_id: ${{ inputs.pr_id }}
          pr_title: ${{ inputs.pr_title }}
          pr_body: ${{ inputs.pr_body }}
      
            
