name: Environment

on:
  workflow_call:
    inputs:
      dryrun:
        type: boolean
        description: Dry run
        required: false
        default: false
      build_env:
        type: string
        description: The environment to build
        required: true
        default: ignore
    outputs:
      selected_env:
        description: Target build environment (devel, staging, production, ignore)
        value: ${{ jobs.def.outputs.selected_env }}
      pullrequest:
        description: Pull request payload from gh-find-current-pr
        value: ${{ jobs.def.outputs.pullrequest }}
      milestone:
        description: Milestone title from the open pull request
        value: ${{ jobs.def.outputs.milestone }}

jobs:
  def:
    runs-on: ubuntu-latest
    outputs:
      pullrequest: ${{ steps.findr.outputs.pr }}
      milestone: ${{ steps.ms.outputs.milestone }}
      selected_env: ${{ steps.def.outputs.selected_env }}
    steps:
      - name: Find pull request
        id: findr
        uses: jwalton/gh-find-current-pr@master
        with:
          state: open
      - name: Find milestone
        id: ms
        if: steps.findr.outputs.number != ''
        uses: actions/github-script@main
        with:
          script: |
            const { data } = await github.request("GET /repos/{owner}/{repo}/pulls/{pr}", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pr: ${{ steps.findr.outputs.number }}
            });
            if (data.milestone) {
              core.info(`This pull request has a milestone set: ${data.milestone.title}`);
              core.setOutput("milestone", data.milestone.title);
            } else {
              core.info(`A maintainer needs to set the milestone for this pull request.`);
            }          
      - id: def
        name: Environment setup
        env:  
          FORCE_ENV: ${{ inputs.build_env }}
          PR: ${{ steps.findr.outputs.pr }}
          MILESTONE: ${{ steps.ms.outputs.milestone }}
          PR_NUMBER: ${{ steps.findr.outputs.number }}
          PR_TITLE: ${{ steps.findr.outputs.title }}
          PR_BODY: ${{ steps.findr.outputs.body }}
          REF: ${{ github.ref }}
          REF_NAME: ${{ github.ref_name }}
          REF_TARGET: ${{ github.base_ref  }}
          REF_TYPE: ${{ github.ref_type }}
          REF_EVENT_NAME: ${{ github.event_name }}
          REF_ACTOR: ${{ github.actor }}
          REF_AUTHOR: ${{ github.event.pusher.name }}
          REF_AUTHOR_EMAIL: ${{ github.event.pusher.email }}
        shell: bash
        run: |
          echo "FORCE_ENV: $FORCE_ENV"
          echo "MILESTONE: $MILESTONE"
          echo "PR: $PR"
          echo "REF_NAME: $REF_NAME"
          echo "REF_TARGET: $REF_TARGET"
          echo "PR_NUMBER: $PR_NUMBER"
          echo "PR_TITLE: $PR_TITLE"
          echo "PR_BODY: $PR_BODY"
          echo "REF_TYPE: $REF_TYPE"
          echo "REF_EVENT_NAME: $REF_EVENT_NAME"
          echo "REF_ACTOR: $REF_ACTOR"
          echo "REF_AUTHOR: $REF_AUTHOR"
          echo "REF_AUTHOR_EMAIL: $REF_AUTHOR_EMAIL"
          echo "DEVEL_BRANCH: $DEVEL_BRANCH"
          SELECTED_ENV=ignore
          if [ "$FORCE_ENV" != "auto" ]; then
            echo "FORCE_ENV '$FORCE_ENV' is not auto"
            SELECTED_ENV=$FORCE_ENV
          elif [ "$REF_TYPE" = "tag" ]; then
            echo "Ref type is tag"
            SELECTED_ENV=production
          else
            case "$REF_NAME" in
              release/*)
                echo "Ref name matches release/*"
                SELECTED_ENV=staging
                ;;
              feature/*)
                echo "Ref name matches feature/*"
                if [ -n "$PR_NUMBER" ]; then
                  echo "PR_NUMBER '$PR_NUMBER' is not empty"
                  SELECTED_ENV=devel
                else
                  echo "PR_NUMBER is empty"
                  SELECTED_ENV=ignore
                fi
                ;;
              *)
                echo "No valid state"
                SELECTED_ENV=ignore
                ;;
            esac
          fi
          echo "SELECTED_ENV: $SELECTED_ENV"
          echo "selected_env=$SELECTED_ENV" >> "$GITHUB_OUTPUT"
